CREATE TABLE modelo_negocio(
	id_modelo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome_modelo VARCHAR(50) NOT NULL, -- Aqui é onde será colocado BARBEARIA, FERRAGEM, LOJA, ...
	descricao TEXT,
	status BOOLEAN DEFAULT TRUE
	
	/* o status controla se o nicho está disponível para novos cadastros na 
	Plataforma SaaS. Se mudar para FALSE, a opção some da tela de cadastro de 
	novos clientes, mas não para o sistema em lojas que já são clientes */
	
);
